### ISSUE TITLE
Renix

### ISSUE THREAD

**Issue by tefnet77** [mike501/speeduino#3]
the last log I sent you it was made with the official release 202201 with a 36-1 decoder so I suppose the sync log won’t be helpful.
With your firmware or older releases I have problems making logs as it creates gaps. Can you integrate the renix decoder with the new release so I can try to make a decent log?

I have installed a 36-1 wheel in the armonic balancer and the motor runs with speeduino, is far from tune but it runs. 
When I tested your firmware I make it run with the 36-1 decoder and once is running I change to the renix decoder, but it wont work.

Just one question, is possible to make the motor run only with the crank sensor with the 60-2-2-2 pattern? If I run the car with the original ECU and disconnect the cam sensor the car keeps running. 

As I’m using paired configuration and 1 channel spark maybe we can try running only with the crank sensor if possible and the try adding the cam sensor.

I’m new to aftermarket ECU's so excuse me if any what I say is a bunch of nosense

**Comment by mike501** [comment]
We can only get the renix decoder pulled into the new release once we've proven it works - so we've got to work through this first. 

Running the 36-1 decoder against your crank pattern and generating a log isn't a problem. Its generated valid data. Interesting that it doesn't work as well with my decoder. Its made me wonder if we could select a different decoder and get better data. I might want you to try again with dual wheel decoder with 66 teeth (or maybe 72 or even 180) - I'll have a think. It does potentially explain why i see a nosync message in the log file i wasn't expecting.

I shouldn't need to do a change to run the code without the cam sensor. Unplug the sensor and ensure the signal wire has a connection to earth / ground (ideally the same ground point the ECU shares but the chassis could be ok). This means the ECU never sees a signal from the cam. I've had a quick look and i think it code will be fine.

Looking at the code and the log file you produced I may need to make a change due to the way i've coded the gaps in the pattern. Can you confirm what settings you have / attach your tune. I'm especially keen to know if you have a VR sensor (and which VR conditioner) or a hall sensor.

**Comment by tefnet77** [comment]
I wasn’t mean to pull the decoder into the official release but to get the last release into your code as it gets better logs.

I will try a dual wheel decoder next time and get you the logs.

I tried your firmware without the cam sensor but it doesn’t work, I will try connecting the signal to ground in the cam sensor.

The ckp is the original one, a vr sensor.
This is the one the car uses:
https://www.quadratec.com/products/55125_0023.htm

I will send you a pic of the vr conditioner as soon as I can.

Attach is my tune
[CurrentTune.zip](https://github.com/mike501/speeduino/files/7842346/CurrentTune.zip)

**Comment by mike501** [comment]
Updating to the latest firmware is on the list of things to do prior to our
being formally accepted. I didn't think anything had been added to the code
that does logging but will recheck.

**Comment by tefnet77** [comment]
Here it is the dual wheel logs with 60, 72 and 180 teeth
there is also a pic of the vr conditioner.
[dual wheel.zip](https://github.com/mike501/speeduino/files/7865350/dual.wheel.zip)

I will try in the next days to run without the cam signal.

**Comment by mike501** [comment]
I've been making a new ardustim trigger wheel. Will check what I've done
with the logs and amend. Once done I'll check the code and let you know
progress.

**Comment by mike501** [comment]
Your logs helped confirm what i thought and i've rebuilt ardustim to match. I've updated the code & have had to code assuming the MAX VR conditioner (using rising trigger edge which is what i believe is needed for the MAX VR conditioner). Revised code on first run seems to work. Will spend some time testing.

**Comment by mike501** [comment]
Code updated (and includes latest firmware 202202 release) and available to test but with the following known issues.

1 it reports double the real RPM - no idea why currently.
2 ignition 3 is at 6k rpm is ~63us incorrect meaning ignition timing is up to 2.3 degrees out. This isn't specific to my code, its in the core firmware and i've raised it on slack to start a discussion.
3 will only work with rising trigger settings (which is what the MAX VR conditioner should need

**Comment by tefnet77** [comment]
Can i test the firmware at this point or i should wait?

**Comment by mike501** [comment]
Give it a go to start the engine, see if it will tick over, rev to 2k (or 4k on the display as it's doubling - double check it is doubling when it ticks over).

Make sure the timing is conservative, the error will increase as reeves rise so a degree retarded and keep under 2.5k and your should be ok for a garage test.

I'll hopefully look later once the wife has gone to bed but I really need help from others on the ignition timing.

**Comment by mike501** [comment]
Not sure the code will work - its not reporting its running at double speed, its trying to run at double the crank trigger speed.

**Comment by mike501** [comment]
So after lots of "why is the rpm double" I think I've got it. Think I've made a mistake in ardustim and it's sending the data at twice the rate when simulating the renix trigger pattern. Code should be good as is for initial testing & I've tested accidentally to 12000rpm.

**Comment by tefnet77** [comment]
It seems that I fried the vr conditioner as I cannot read from the renix wheel nor the 36-1. I tried another Arduino and another board and the problem persist.

I hope that I can fix it in the next few days/weeks.

**Comment by mike501** [comment]
No problem.

I posted on the forum asking a question on the size of the flywheel.
Something occurred this week that the measurements of the teeth don't add
up. The gap is physically 3 teeth not 2, this means the flywheel is really
46 teeth in size. If I'm right all the measurements I've used to calculate
angles is incorrect.

This trigger pattern is difficult!

Not sure how easy, but if you could measure the size of a tooth, the gap
between teeth, the size of the gap and diameter of the flywheel that would
be amazing (don't go splitting the engine - only if it's easy)

**Comment by tefnet77** [comment]
Sorry I couldn’t take measurements of the flywheel, is impossible without removing the transmission.

Watching pictures of the flywheel on internet it seems that the tooth sizes are all equal.
These are the pictures if they are in any help.
![1](https://user-images.githubusercontent.com/63187354/151697908-9012423f-78dd-4323-8a7e-c0d5b80f29a3.png)
![6b49bfbb9c84129b06efe2c3033cf0cd](https://user-images.githubusercontent.com/63187354/151697914-43d065a3-5cd4-483e-984f-14bffc30cc4d.jpg)



I’m still waiting the chip to fix the vr conditioner.

**Comment by mike501** [comment]
Realised I've not updated this. Tooth sizes work out to 44 teeth with 2 missing. My concern wasn't valid. It is important to get the rising/ falling correct otherwise the gap doesn't appear to be a double gap but two slightly larger than normal teeth.

**Comment by tefnet77** [comment]
I am in the process of install a dropbear, i has remove the original wiring and I making a new one, I hope I can test the firmware in a few weeks

**Comment by mike501** [comment]
I updated the forum but not here. My concerns over the flywheel were
unfounded. Have someone on Facebook who's started to test, the more testers
the quicker we'll get confidence it works. Likely to do an update on the
next few days to get all the latest fixes from the Dev branch of the
firmware.

**Comment by mike501** [comment]
code merged into release in 2023
